# Generated by Django 4.1.3 on 2022-11-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
    ]
