# Generated by Django 4.1.3 on 2022-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='user_type',
            field=models.CharField(choices=[('d', 'Doctor'), ('c', 'Cashier'), ('l', 'Lab Technician'), ('p', 'Pharmacist')], default='', max_length=1, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('d', 'Doctor'), ('c', 'Cashier'), ('l', 'Lab Technician'), ('p', 'Pharmacist')], default='', max_length=1, verbose_name='User Type'),
        ),
    ]
