# Generated by Django 4.1.3 on 2022-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_historicaluser_user_type_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='user_type',
            field=models.CharField(choices=[('d', 'Doctor'), ('c', 'Cashier'), ('l', 'Lab Technician'), ('p', 'Pharmacist')], max_length=1, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('d', 'Doctor'), ('c', 'Cashier'), ('l', 'Lab Technician'), ('p', 'Pharmacist')], max_length=1, verbose_name='User Type'),
        ),
    ]
