# Generated by Django 4.1.3 on 2022-11-13 23:23

from django.db import migrations
import native_shortuuid.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicaluser_uuid_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='uuid',
            field=native_shortuuid.fields.NativeShortUUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=native_shortuuid.fields.NativeShortUUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
