# Generated by Django 4.1.3 on 2022-11-12 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Middle Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('id_number', models.CharField(max_length=50, unique=True, verbose_name='ID Number')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('signs_and_symptoms', models.TextField(verbose_name='Signs and Symptoms')),
                ('test', models.TextField(verbose_name='Diagnosis')),
                ('test_result', models.TextField(verbose_name='Test Result')),
                ('treatment', models.TextField(verbose_name='Treatment')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='records.patient')),
            ],
            options={
                'verbose_name': 'Patient Record',
                'verbose_name_plural': 'Patient Records',
                'ordering': ['patient', 'created'],
            },
        ),
    ]
