# Generated by Django 4.1.3 on 2022-11-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='id_number',
            new_name='patient_id_number',
        ),
    ]
