# Generated by Django 4.1.3 on 2022-11-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_id_number_patient_patient_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='signs_and_symptoms',
            field=models.TextField(blank=True, default='', verbose_name='Signs and Symptoms'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='test',
            field=models.TextField(blank=True, default='', verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='test_result',
            field=models.TextField(blank=True, default='', verbose_name='Test Result'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='treatment',
            field=models.TextField(default='', verbose_name='Treatment'),
        ),
    ]
