# Generated by Django 4.1.3 on 2022-11-13 23:29

from django.db import migrations
import native_shortuuid.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_patientrecord_signs_and_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=native_shortuuid.fields.NativeShortUUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='uuid',
            field=native_shortuuid.fields.NativeShortUUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
