# Generated by Django 4.1.3 on 2022-11-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_patient_uuid_patientrecord_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.CharField(choices=[('Kakuma Ward', 'Kakuma Ward'), ('Lapur Ward', 'Lapur Ward'), ('Lete Ward', 'Lete Ward'), ('Songot Ward', 'Songot Ward'), ('Kalobeyei Ward', 'Kalobeyei Ward'), ('Lokichogio', 'Lokichogio'), ('Nanaam Ward', 'Nanaam Ward')], default='', max_length=50, verbose_name='Ward'),
        ),
    ]
