# Generated by Django 4.1.3 on 2022-11-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_patient_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='uuid',
        ),
    ]
