# Generated by Django 4.1.3 on 2022-11-22 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_remove_patientrecord_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrecord',
            options={'verbose_name': 'Patient Record', 'verbose_name_plural': 'Patient Records'},
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='created',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='patient_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='records.patient'),
            preserve_default=False,
        ),
    ]
